### ISSUE TITLE
각자 RSS피드 추천하고 opml파일로 배포하면 좋을듯

### ISSUE THREAD

**Issue by miaekim** [benjioh5/CS-Univ-Wiki#10]
물론 `해커뉴스`+`MIT technology review`+`IEEE Spectrum`만 해도 읽을게 넘쳐나겠지만.. 
아 그리고 `acm computing survey`.. 뭐 얘는 한달에 하나 나오니..

저것들은 거의 뉴스위주고 개인적인 사견 읽기는 힘든데,
개인 블로그는 어느게 좋은 블로그인지 알기도 힘들어서..
뭔가 변기라면 좋은 글 많이 구독하지않을까?

**Comment by benjioh5** [comment]
1. [개발자 블로그 RSS 모음](https://indidev.net/forum/viewtopic.php?p=1424)
2. [awesome-devblog](https://github.com/sarojaba/awesome-devblog)
3. [다음 DNA Lens](http://dna.daum.net/lens/)

정도만 봐도 무방하지 않을까 싶습니다. 그 외에도 디자인/예술/정치/경제 관련으로 더 있긴 한데, 이거 정리해서 올리는 것도 일임 ㅠㅠ

**Comment by benjioh5** [comment]
정보 검색/RSS 파트에 이 부분 추가 예정
기존에 내가 보고 있는 RSS 목록도 추가할 예정임
