### ISSUE TITLE
공학인증 관련한 항목을 추가하는건 어떨까요?

### ISSUE THREAD

**Issue by dohvis** [benjioh5/CS-Univ-Wiki#104]
제가 지금 이거때문에 꽤나 골머리를 앓고 있어서.. 있다면 좋을 것 같다는 생각을 했습니다

**Comment by benjioh5** [comment]
네 추가하도록 하죠!

**Comment by miaekim** [comment]
cs univ wiki는 오픈소스기 때문에 본인이 작성하시고 풀리퀘를 올리시는걸 적극 권장합니다.
