### ISSUE TITLE
SW 개발병 최소지원 자격이 변경됐습니다

### ISSUE THREAD

**Issue by mingkyme** [benjioh5/CS-Univ-Wiki#105]
석사 재학 이상만 지원 가능하게 2021.02.01 일자로 변경됐네요

**Comment by benjioh5** [comment]
메인테인해야하는데 ㅠㅠㅠ 죄송합니다. 이걸 많이 늦게 봤네요

**Comment by mingkyme** [comment]
이거 close한 이유가 
SW개발병 안내 홈페이지는
2021-02-10 일자 업데이트 됐다곤 나오는데 학력부분 제한이 없습니다
https://www.mma.go.kr/contents.do?mc=mma0001989


제가 확인한 부분은 이번에 뽑는 1명뽑는 선발에만 적용되는 것으로 추측됩니다
![image](https://user-images.githubusercontent.com/45954551/107874411-ece24d80-6efc-11eb-8d47-64f11d3d5b76.png)
이에 close했습니다 확인 후 다시 reopen 하겠습니다
https://www.mma.go.kr/board/boardView.do?gesipan_id=93&gsgeul_no=1506606&pageIndex=1&searchCondition=&searchKeyword=&pageUnit=10&mc=usr0000150&jbc_gonggibodo=0

**Comment by benjioh5** [comment]
넵 알겠습니다!
