### ISSUE TITLE
도메인 추가

### ISSUE THREAD

**Issue by benjioh5** [benjioh5/CS-Univ-Wiki#33]
[gollum](https://github.com/gollum/gollum) 으로 위키 운영할 예정
~~~.wiki 도메인 구입하여, 도메인, 서브도메인 설정 할 것.

**Comment by benjioh5** [comment]
#9 에서 프로젝트 이름 결정되면 바로 도메인 적용할 생각.
현재 후보는 Univ wiki (유니브 위키) 임

**Comment by miaekim** [comment]
univ.wiki
음 괜찮아보임
cs.wiki
로 하는게 좀 더 구체적인거 같지만
왠지 변기가 다른 과에 필요한것도 추가하려나 ㅎㅎ??

**Comment by benjioh5** [comment]
cs univ wiki

**Comment by MaybeS** [comment]
univ wiki로 해두고 cs카테고리부터 채워나가는 식으로..

**Comment by benjioh5** [comment]
@MaybeS 그럴 생각이었.....

**Comment by benjioh5** [comment]
일단 http://cs.univ.wiki 로 갑니다. 보는 눈이 워낙 많아서, 최대한 빨리 모든 문서를 작성하고 퇴고를 하는 걸로 목표를 잡도록하겠습니다.
