### ISSUE TITLE
컨퍼런스 항목 분리

### ISSUE THREAD

**Issue by miaekim** [benjioh5/CS-Univ-Wiki#56]
1. 새로 학술쪽 컨퍼런스 항목을 만들까나?
2. 논문 하위항목에 컨퍼런스/저널을 넣을까나?

http://academic.research.microsoft.com/RankList?entitytype=3&topDomainID=2&subDomainID=0

컨퍼런스 항목에 얘내들이 없으면 안되잖아여 ㅠㅠ

**Comment by benjioh5** [comment]
네 학술쪽에 새롭게 만들죠....
