### ISSUE TITLE
프로젝트 이름 변경

### ISSUE THREAD

**Issue by benjioh5** [benjioh5/CS-Univ-Wiki#9]
1. 단순 ICEWALL에서 내부적으로 사용할 문서가 아니다.
7. 현재 타 동아리 (e.g. 퀵스) 등에서 활용할 수 있는 수준으로 작성되어질 예정이다.
2. 현재 참여한 사람들의 구성이 ICEWALL에 치중되어 있지만, 공개 및 홍보를 하면 분포가 변할 가능성이 크다.
3. 컴퓨터공학 지식만 넣을 예정이 아닐 예정이다.
4. 위키 형태로 운영할 가능성도 존재한다.

최종적으로, 이에 걸맞는 프로젝트 이름을 정하는 것이 필요하다고 생각합니다. 이렇게 이름을 지은 이후 올게나이제이션을 새로 파고, 그 곳에서 관리하는 쪽으로 방향을 잡고 있습니다.

**Comment by miaekim** [comment]
과연 컴공계의 학교대사전이 될런지 (?)

**Comment by benjioh5** [comment]
@miaekim 나무위키만 되도 눈물이 날 듯

**Comment by benjioh5** [comment]
Univ Wiki 로 이름을 생각 중인데, 괜찮은 이름 있으면 추천 해 주세요 :)

**Comment by benjioh5** [comment]
변경 완료
