### ISSUE TITLE
now Topic!

### ISSUE THREAD

**Issue by MaybeS** [benjioh5/CS-Univ-Wiki#93]
[이제 깃허브에서도 토픽을 추가할 수 있게되었습니당 !! ](https://github.com/blog/2309-introducing-topics)

우리도 토픽을 넣는것은 어떤가요.

@benjioh5

**Comment by miaekim** [comment]
추천 토픽 목록

- tip
- tutorial
- university
- computer science
- security

**Comment by benjioh5** [comment]
Oh no.....

**Comment by benjioh5** [comment]
- computer-science
- gitbook
- security
- tips
- tutorial
- university
- korean
- wiki
로 등록 완료했습니다. :)

**Comment by miaekim** [comment]
토픽 등록했으니 이제 닫을까욤?
